[build]
builder = "nixpacks"

[deploy]
startCommand = "python server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 10
healthcheckInterval = 30