[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker server_final:app --bind 0.0.0.0:$PORT --timeout 300 --keep-alive 2 --max-requests 1000 --preload"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 60

[[services]]
name = "siports-production"
